# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/abel/Downloads/sr_muxVioIla/shiftReg/Arty_Master_v2.xdc

# Block Designs: bd/ila/ila.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila || ORIG_REF_NAME==ila} -quiet] -quiet

# IP: bd/ila/ip/ila_ila_0_0/ila_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_ila_0_0 || ORIG_REF_NAME==ila_ila_0_0} -quiet] -quiet

# Block Designs: bd/vio/vio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio || ORIG_REF_NAME==vio} -quiet] -quiet

# IP: bd/vio/ip/vio_vio_0_0/vio_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vio_vio_0_0 || ORIG_REF_NAME==vio_vio_0_0} -quiet] -quiet

# XDC: /home/abel/Documents/vivado_projects/test_VIO_ILA/test_VIO_ILA.gen/sources_1/bd/ila/ila_ooc.xdc

# XDC: /home/abel/Documents/vivado_projects/test_VIO_ILA/test_VIO_ILA.gen/sources_1/bd/vio/vio_ooc.xdc
